# Lista 7: Numpy

### Nome: Gustavo Machado Pires | DRE: 122115709

## Bibliotecas

In [14]:
import random
import math
import numpy as np

## 1. Lançamento de Dados

In [15]:

def dado():
    total = 0
    for _ in range(100):
        total += random.randint(1, 6)
    return total

resultado = dado()
print(f'A soma dos 100 lancamentos eh: {resultado}')

A soma dos 100 lancamentos eh: 321


## 2. Diagonal Principal

In [16]:
matriz = np.zeros((4, 4))
np.fill_diagonal(matriz, 1)
print(matriz)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 3. Multiplicando Array

In [17]:
matriz = np.ones((3, 3)) 
print(matriz *5)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


## 4. Interação com Usuário

In [21]:
matriz = np.empty((2,3))
for i in range(2):
    for j in range(3):
        matriz[i,j] = input(f'digite um valor para i: {i} e para j: {j}')
print(matriz)

[[6. 3. 5.]
 [8. 7. 6.]]


## 5. POO + 5.1

In [24]:
class ArrayNumpy:
    def __init__(self):
        self.array = None
        
    def criar_zeros(self, shape):
        self.array = np.zeros(shape)
        return self.array
    
    def criar_uns(self, shape):
        self.array = np.ones(shape)
        return self.array
    
    def criar_vazios(self, shape):
        self.array = np.empty(shape)
        return self.array
    
    def mostrar_array(self):
        if self.array is not None:
            print(self.array)
        else:
            print("Nenhum array foi criado ainda.")
            
array1 = ArrayNumpy()
array1.criar_zeros((3,3))
array1.mostrar_array()
array1.criar_uns((4,4))
array1.mostrar_array()
array1.criar_vazios((2,2))
array1.mostrar_array()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]]
